baseurl = "https://valticus.pro/"
title = "Valticus"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "valticus"


[services.disqus]
  shortname = "" # Enable Disqus by entering your Disqus shortname
[services.googleAnalytics]
  ID = "G-39H9NV2Z47" # Enable Google Analytics by entering your tracking ID

[Author] # Used in authorbox
  name = "Val Paliy"
  bio = "I am a programmer who writes about everything."
  avatar = "img/avatar.png"

[Params]
  description = "Val Paliy's Personal blog about everything" # Site description. Used in meta description
  copyright = "Valticus" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files



[Params.style.vars]
  highlightColor = "#0056B9" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/logo.png" # Logo image. Path relative to "static"
  title = "Valticus" # Logo title, otherwise will use site title
  subtitle = "It's all about text!" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  facebook = "Valticus"
  email = "valticus81@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "About me"
  url = "https://valticus.pro/about/"
[[Params.widgets.social.custom]]
  title = "My portfolio"
  url = "https://valticus.pro/portfolio/"
[[Params.widgets.social.custom]]
  title = "My IDE Settings"
  url = "https://valticus.pro/ide-settings/"


[[Params.widgets.social.custom]]
  title = "LinkedIn"
  url = "https://www.linkedin.com/company/valticus/"
[[Params.widgets.social.custom]]
  title = "Medium"
  url = "https://valticus.medium.com/"

[Params.widgets.search]
  cached = false # activate cache if true
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""
